spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_portal-comunic
    username: pc_user
    password: pc_pass
  jpa:
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true